version: '3'

services:
  dio-postgres-compose:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "Postgres2021#"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  dio-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "infra@dio.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021#"
    ports:
      - "16543:80"
    depends_on:
      - dio-postgres-compose
    networks:
      - postgres-compose-network
  #dio-api:
  #  build: ./
  #  restart: on-failure
  #  ports:
  #    - 8899:8899
  #  environment:
  #    - DATABASE_HOST=${DATABASE_HOST}
  #    - DATABASE_USER=${DATABASE_USER}
  #    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #    - DATABASE_NAME=${DATABASE_NAME}
  #    - DATABASE_PORT=${DATABASE_PORT}
  #  depends_on:
  #    - dio-postgres-compose
  #  networks:
  #    - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
